# check docker hub
version: "3.8"
services:
  frontend: # arbitray name
    build: # build Dockerfile
      context: ./Docker/frontend # path of the terget docker file
    ports:
        - 3000:3000 # <local port>:<container port>
    volumes: # sync directory to container
      - ./frontend:/app # <local directory path>:<container directory path>
    command: bash -c "npm run dev" # will be executed after built
    environment: # environment variable
      - WATCHPACK_POLLING=true # envitonment　いるかわからん　nodemon的なやつ?
  db:
    image: mysql:8.0 # check docker hub
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - arbitrayName:/var/lib/mysql #<name>: <path for saving data>
  wordpress:
    image: wordpress
    ports:
      - "8089:80"
    depends_on: # starts after the specified container
      - mysql # <servise name>
    environment:
      WORD_PRESS_DB_HOST: mysql
      WORD_PRESS_DB_USER: root
      WORD_PRESS_DB_PASSWORD: "coffee"
      WORD_PRESS_DB_NAME: wordpress
    networks: #
      ohyeah: # <arbitray naem>
        ipv4_address: "192.168.92.25" # <arbitray ip address>

  mysql:
    image: "mysql"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "coffee"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      ohyeah:
        ipv4_address: "192.168.92.26"
networks:
  ohyeah:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"

volumes:
  ninninonamae: {}